//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditPand.BD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interes
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public decimal Monto_regular { get; set; }
        public decimal Monto_morosidad { get; set; }
    }
}
