//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditPand.BD.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Solicitud
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public int Límite { get; set; }

        [Display(Name = "Extrafinanciamiento")]
        public int Monto_extra { get; set; }

        [Display(Name = "Activación")]
        public System.DateTime Fecha_activación { get; set; }
        public bool Internacional { get; set; }

        [Display(Name = "Usuario")]
        public int IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
